version: "3.8"

services:
  db:
    image: postgres:14.9
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5431:5431
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5431/db
    ports:
      - 8080:8080
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 2

volumes:
  db:
    driver: local
